NeurProjects/neur-app

- LOCAL_DEV.md
- README.md
Documentation for local development changes
> Add local dev docs

- src/components/dashboard/wallet-card.tsx
- src/components/ui/copyable-text.tsx
> Fix tx truncate on SOL transfer success dialog

- src/ai/solana/dexscreener.tsx
- src/lib/utils/format.ts
> Fix dexscreener links

- src/app/(user)/home/home-content.tsx
- src/components/dashboard/app-sidebar-conversations.tsx
When a new conversation is created, we can refresh after the chat has started
> Fixes spam on conversation endpoint

- CHANGELOGS.md
- package.json
- src/app/api/chat/route.ts
Hotfix for confirmations / message context limit with gpt4o, confirmed fix working on beta
> v0.1.9 Update

- package.json
- patches/solana-agent-kit.patch
- pnpm-lock.yaml
- src/ai/solana/dexscreener.tsx
- src/ai/solana/solana.tsx
Handle result when dexscreener fails to find the token
> Upgraded solana-agent-kit to handle decimals

- CHANGELOGS.md
- package.json
- patches/solana-agent-kit.patch
- pnpm-lock.yaml
- prisma/migrations/20250102065518_add_message_tokens/migration.sql
- prisma/migrations/20250102200737_message_tokens_drop_unique_user_id/migration.sql
- prisma/migrations/20250103193523_token_stats_multiple_types/migration.sql
- prisma/schema.prisma
- src/ai/providers.tsx
- src/ai/solana/dexscreener.tsx
- src/ai/solana/solana.tsx
- src/app/(user)/chat/[id]/chat-interface.tsx
- src/app/api/chat/route.ts
- src/server/db/queries.ts
- Message token tracking (model usage) for backend analysis
- Fixes to solana-agent-kit implementation for decimal handling
> v0.1.10 Update

- CHANGELOGS.md
- package.json
- patches/solana-agent-kit.patch
- pnpm-lock.yaml
- prisma/migrations/20250102065518_add_message_tokens/migration.sql
- prisma/schema.prisma
- src/ai/solana/dexscreener.tsx
- src/ai/solana/solana.tsx
- src/app/api/chat/route.ts
- src/server/db/queries.ts
The best community Ever ♥️ and BULLISH
> Gib bounty neu488393

- LOCAL_DEV.md
- src/ai/providers.tsx
Allows usage of PPQ with `claude-3.5-sonnet` model
> Custom PPQ Model Provider

- CHANGELOGS.md
- LOCAL_DEV.md
- package.json
- src/ai/providers.tsx
- Utilize PPQ for AI model endpoint
> v0.1.12 Update

- src/ai/generic/util.tsx
- src/ai/providers.tsx
- src/app/(user)/chat/[id]/chat-interface.tsx
- src/app/api/chat/route.ts
- src/lib/utils/ai.ts
- src/server/actions/ai.ts
- src/server/db/queries.ts
- src/types/util.ts
> Confirm / Deny with Chat Message

- src/ai/generic/action.tsx
- src/ai/generic/telegram.tsx
- src/ai/providers.tsx
- src/server/actions/action.ts
- src/server/actions/telegram.ts
When creating an action to send a telegram notification, verify the user has setup the bot to be able to message them.
Closes #88
> Verify TG setup before creating an action

- prisma/migrations/20250108170751_add_telegram_chat_table/migration.sql
- prisma/schema.prisma
- src/ai/generic/telegram.tsx
- src/server/actions/telegram.ts
- src/server/db/queries.ts
> Fix for unknown telegram chat ID

- src/ai/providers.tsx
@backwardsmap any other useful datapoints we can add here?
> Seed system prompt with time

- src/ai/solana/solana.tsx
- src/components/ui/table.tsx
- src/lib/solana/helius.ts
Fixes #129 
Style changes as well
> Quick fix for token holders with more than 50k holders

- src/ai/solana/solana.tsx
- src/app/(user)/chat/[id]/chat-interface.tsx
- src/app/(user)/home/home-content.tsx
- src/app/(user)/layout.tsx
- src/app/layout.tsx
- src/components/confimation.tsx
- src/components/message/tool-result.tsx
- src/components/message/wallet-portfolio.tsx
- src/lib/constants.ts
> Mobile UI fixes

- src/app/(user)/faq/page.tsx
> fix: typo in faq

- CHANGELOGS.md
- package.json
- src/ai/providers.tsx
- src/server/actions/action.ts
- Improved action graceful failure logic
> Release v0.2.2 - Graceful automation failure conditions

- prisma/migrations/20250123201805_add_conversation_read/migration.sql
- prisma/schema.prisma
- src/ai/providers.tsx
- src/ai/solana/jupiter.tsx
- src/ai/solana/solana.tsx
- src/app/(user)/chat/[id]/chat-interface.tsx
- src/app/(user)/home/home-content.tsx
- src/app/api/chat/route.ts
- src/app/globals.css
- src/components/dashboard/app-sidebar-automations.tsx
- src/components/dashboard/app-sidebar-conversations.tsx
- src/hooks/store/conversations.ts
- src/hooks/use-conversations.ts
- src/hooks/use-polling.ts
- src/lib/events.ts
- src/server/actions/action.ts
- src/server/actions/ai.ts
- src/server/actions/conversation.ts
- src/server/actions/orchestrator.ts
- src/server/db/queries.ts
- src/server/utils/index.ts
- tailwind.config.ts
- Openrouter provider priority mapping
- Action status icons
- Conversation "notification" icons
> Performance enhancements, UI improvements

- src/ai/providers.tsx
- src/server/actions/user.ts
Only add the PRIVY_SIGNING_KEY if it is defined
> Only set override the fetch if pointing to openrouter

- src/ai/providers.tsx
- src/app/(user)/chat/[id]/chat-interface.tsx
- src/components/message/tool-result.tsx
- src/components/subscription/subscription-section.tsx
> Fix client error when unknown tool invocation result is encountered

- src/ai/solana/magic-eden.tsx
Some stats aren't available when on a new NFT collection
> Handle missing stats on new NFT collection

- src/app/(user)/home/conversation-input.tsx
#183 solved!
[Screencast from 2025-02-03 11-50-33.webm](https://github.com/user-attachments/assets/05709690-b113-4799-953e-4c513ac3da4d)
> fixed textarea size and made it scrollable

- src/app/(user)/chat/[id]/chat-interface.tsx
- src/components/ui/sidebar.tsx
solving #193 
the issue was occurring when the address bar of the browser was on top of the actual website screen, hiding account button.
Therefore even without the changes made through this PR, it was working fine in phantom browser (where the website content ends before the bottom bar) :
https://github.com/user-attachments/assets/20560644-2451-435e-b96b-f7dbebe75656
But it wasn't working on browsers like brave, where the bottom bar of the website were on the top of site content hiding it.
Fixed In this PR:
https://github.com/user-attachments/assets/c21108d8-66ab-46b2-82c5-dfbc4825bfeb
> mobile Sidebar fixed
